# Generated by Django 2.0.2 on 2019-09-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='blog_posts',
        ),
    ]
